#!/bin/bash
#Small script to flush Memcached


if pgrep memcached &> /dev/null; then
    printf '%s\n' 'Memcached is not running!'
else
    nc -w 3 localhost 11211 <<< flush_all
    printf '%s\n' 'Memcached cache was flushed! :)'
fi
