#!/bin/bash
# written by staticsafe, ze, jayms, chris and ckpro
# fixed various nasty things (thanks neurolysis)

arch=$(uname -m)


die() {
	printf '%s\n' "$@" >&2
	exit 1
}

# Installation
if [[ ! -d ~/bin ]]; then
	mkdir ~/bin || die 'Failed to create ~/bin.'
fi


if [[ "$SHELL" == "/usr/bin/zsh" || "$SHELL" == "/bin/zsh" ]]
    printf '%s\n' 'export PATH=$HOME/bin:$PATH' >> ~/.zshenv
elif [[ "$SHELL" == "/bin/bash" ]]
    printf '%s\n' 'PATH="$HOME/bin:$PATH"' >> ~/.bashrc
else
    printf '%s\n' 'The script does not support your default shell. Please add $HOME/bin to your path manually'
fi


case "${arch}" in
	i686|i586) wget -O ~/bin/mtn http://dl.dropbox.com/u/34659045/mtn-32 || die 'Failed to download mtn.' ;;
	x86_64) wget -O ~/bin/mtn http://dl.dropbox.com/u/34659045/mtn-64 || die 'Failed to download mtn.' ;;
	*) die "Unknown arch '${arch}', aborting." ;;
esac
chmod a+x ~/bin/mtn

# Get font
wget -O ~/bin/Terminus.ttf http://files.ax86.net/terminus-ttf/4.36/TerminusMedium-4.36.ttf

# Create mkscr bash script
cat > ~/bin/mkscr << 'EOF'
#!/bin/bash
for arg; do
	mtn -f ~/bin/Terminus.ttf -c 4 -r 8 -w 1280 -b 0.6 -D6 -T "Screens for hey.fux0r.eu" "${arg}"
done
EOF

chmod a+x ~/bin/mkscr

printf '%s\n' 'Done. Happy screenshotting!'

