#!/usr/bin/env bash
#Sets up a fully working development environment for Caffeine Linux developers on Debian based systems

#WARNING : THIS SCRIPT IS NOW OBSOLETE! Please refer to the caffeine-linux git repo for the current version!

die() {
printf '%s\n' "$@" >&2
exit 1
}

#Caffeine Linux repo stuff (installs all dev related stuff like svn, git etc.)

wget -O caffeine.asc http://foxwolfblood.me/repo/pubkey || die 'failed to download caffeine.asc'
sudo apt-key add caffeine.asc
cp /etc/apt/sources.list $HOME/sources.list
sudo chmod 777 $HOME/sources.list
echo 'deb http://foxwolfblood.me/repo alpha caffeine' >> $HOME/sources.list
sudo mv $HOME/sources.list /etc/apt/sources.list
sudo chmod 644 /etc/apt/sources.list
sudo chown root:root /etc/apt/sources.list
sudo apt-get update
sudo apt-get install caffeinelinux-developer subversion #the caffeinelinux-developer package does NOT install svn
sudo -k

#Setup editors
#vim is just an example, feel free to use your editor of choice, this script was written in Geany.

cd $HOME
if [[ ! -e .vimrc ]]; then
	wget -O .vimrc http://dl.dropbox.com/u/2888062/vimrc || die 'failed to download .vimrc.' 
else
	printf '%s\n' 'You already have a .vimrc, doing nothing for this step.'
fi

#Setup dev directories (feel free to change/remove this for your convenience)

cd $HOME

if [[ ! -d dev ]]; then
	mkdir dev
	cd ./dev
	svn co https://caffeine-linux.svn.sourceforge.net/svnroot/caffeine-linux caffeine-linux 
else
	cd ./dev
	svn co https://caffeine-linux.svn.sourceforge.net/svnroot/caffeine-linux caffeine-linux
fi 

exit
